### ISSUE TITLE
requote_url adds extra %C2 on encountering % symbols

### ISSUE THREAD

**Issue by talyian** [Yelp/yelp_uri#12]
I would expect 'http://a.b/c?%aa' to be a fixed point of requote_url

instead it becomes 'http://a.b/c?%C2%AA'

**Comment by asottile** [comment]
%aa is latin-1 and not utf-8 so I think the conversion makes sense?

**Comment by bukzor** [comment]
Naw those are two separate URLs. My patch yesterday wasn't quite right, apparently.

**Comment by bukzor** [comment]
Ah that's right @talyian, we "correct" latin1 to be utf-8 as part of our normalization.
Character \uAA is UTF-8 \xC2AA.

Is this a bug for you?

**Comment by bukzor** [comment]
More rationale: A de-facto standard on the internet is percent-encoded-utf8 in query strings. Interpreted that way, your input isn't really decodable.  Since the purpose of this function is to reformat poorly-encoded user input, rather than throwing an error, we interpret it as latin1 and encode to utf8, resulting in a URL that is decodable, albeit with not exactly the same bytes as the input.

**Comment by talyian** [comment]
the test cases I was looking at were not the most RFC-compliant uris. Closing this issue, then,.
